### ISSUE TITLE
checking audio file

### ISSUE THREAD

**Issue by dimanshu** [vineeths96/Spoken-Keyword-Spotting#3]
@vineeths96 how to check the audio through this model .? i don't want to stream.

what should be the length of the audio file and sample rate ?

**Comment by vineeths96** [comment]
Please take a look [here](https://github.com/vineeths96/Spoken-Keyword-Spotting/blob/master/src/model_test.py#L43-L62) and [here](https://github.com/vineeths96/Spoken-Keyword-Spotting/blob/master/src/parameters.py#L3-L4).
