### ISSUE TITLE
When pip install i found a problem.

### ISSUE THREAD

**Issue by kabrate** [vineeths96/Spoken-Keyword-Spotting#5]
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.0.15.
My python version is 3.8.2.

**Comment by vineeths96** [comment]
It seems that PIP wheels are not available for `mkl-fft` now. 

(Assuming you are using Conda environment) Could you remove the line from the `requirement.txt` file and manually install using `conda install mkl-fft==1.0.15`

**Comment by kabrate** [comment]
> 似乎PIP轮暂时不可用`mkl-fft`。
> 
> （假设您使用的是Conda环境）是否可以从`requirement.txt`文件中删除该行并使用以下命令手动安装`conda install mkl-fft==1.0.15`

Thank you!

**Comment by kabrate** [comment]
Besides, i met that a problem when installing pyaudio. I install it in whl form. Then it is able to run.
